/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.erikthered;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App.main("C:\\Users\\Erik Nelson\\projects\\words\\src\\test\\resources\\test_common.txt",
                "C:\\Users\\Erik Nelson\\projects\\words\\src\\test\\resources\\test_text.txt");
    }
}
